version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/http.d:/etc/nginx/http.d"
      - "./nginx/stream.d:/etc/nginx/stream.d"
      - "./nginx/cert:/etc/nginx/cert"
      - "./nginx/log:/var/log/nginx"
      - "./www:/var/www/"

  php:
    build: ./php
    container_name: php-fpm
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./php/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "./php/php-fpm.d:/usr/local/etc/php-fpm.d"
      - "./www:/var/www/"

  mariadb:
    image: mariadb:lts
    container_name: mariadb
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    volumes:
      - "./mariadb/data:/var/lib/mysql"

  redis:
    image: redis
    container_name: redis
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./redis/:/etc/redis/"
    command: redis-server /etc/redis/redis.conf
